### ISSUE TITLE
 ImportError: cannot import name objects

### ISSUE THREAD

**Issue by R-Sila** [facebook/facebook-python-ads-sdk#323] opened 2017-05-01 10:03 UTC
from facebookads import FacebookAdsApi
from facebookads import objects
my_app_id = 'my_app_id'
my_app_secret = 'my_app_secret'
my_access_token = 'my_access_token'
FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)

me = objects.AdUser(fbid='me')
my_accounts = list(me.get_ad_accounts())
print my_accounts

**Comment by devinmcginty** [comment] 2017-05-01 15:17
`objects` has been deprecated as of 2.8.2 in favor of using `adobjects`. `AdUser` was a wrapper for `adobjects.adaccountuser.AdAccountUser`.

**Comment by uppercasebrands** [comment] 2017-05-01 15:25
@devinmcginty is right. This is a duplicate of https://github.com/facebook/facebook-python-ads-sdk/issues/315.

**Closed** 2017-05-01 17:15 UTC
