### ISSUE TITLE
batch remote-create error because of id=None

### ISSUE THREAD

**Issue by linpingta** [facebook/facebook-python-ads-sdk#35] opened 2015-03-07 03:10 UTC
Hi guys,

Thanks a lot for making this, but I meet one error when do batch remote_create of campaign/adset/ads and I am not sure whether it's a mistake.

My code like:
    
    api_batch = api.new_batch()

     // def callback function

    campaign.update({
        AdCampaign.Field.name: 'Seattle Ad Campaign',
        AdCampaign.Field.objective: AdCampaign.Objective.website_clicks,
        AdCampaign.Field.status: AdCampaign.Status.paused,
    })

    campaign.remote_create(batch=api_batch,success=callback_success,failure=callback_failure)

    api.execute()

And it raises error like:

    Traceback (most recent call last):
      File "create_ad.py", line 164, in <module>
       campaign.remote_create(batch=api_batch,success=callback_success,failure=callback_failure)
      File "/home/chutong/fb_api_test/facebookads/objects.py", line 529, in remote_create
        failure=callback_failure,
      File "/home/chutong/fb_api_test/facebookads/api.py", line 373, in add
        keyvals.append("%s=%s" % (key, urllib.parse.quote(params[key])))
      File "/usr/local/lib/python2.7/urllib.py", line 1225, in quote
        raise TypeError('None object cannot be quoted')
      TypeError: None object cannot be quoted

The reason is in 

        for key in params:
                keyvals.append("%s=%s" % (key, urllib.parse.quote(params[key])))

**params contains key='id' which has value None**,  it couldn't be treated as string here.

Should a judgement for value added here or do I make a wrong usage of batch remote create here?

Thanks for your help.

**Comment by m-vdb** [comment] 2015-05-13 20:40
duplicate of #35, but I think it's an actual bug

**Comment by facebook-github-bot-9** [comment] 2015-08-04 18:04
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by rituparnamukherjee** [comment] 2016-04-05 18:27
Closing this out. WIll track with #30

**Closed by rituparnamukherjee** 2016-04-05 18:27 UTC
