### ISSUE TITLE
"AdsPixel.get_stats()" raise FacebookBadObjectError("Bad data to set object data") exception

### ISSUE THREAD

**Issue by yanbf** [facebook/facebook-python-ads-sdk#212] opened 2016-06-16 09:17 UTC
facebookads/adobjects/objectparser.py(78) --->AbstractObject.create_object(....)
facebookads/adobjects/abstractobject.py(166)--->new_object._set_data(data)

here, data = [{u'count': 10, u'value': u'PageView'}]

facebookads/adobjects/abstractobject.py(89)--->
if hasattr(data, 'items'):   **# data has no item**
raise FacebookBadObjectError("Bad data to set object data")

**Comment by ekoly** [comment] 2016-06-16 14:22
This appears to be a duplicate of https://github.com/facebook/facebook-python-ads-sdk/issues/208. I have a pull request pending to fix the issue, under https://github.com/facebook/facebook-python-ads-sdk/pull/209.

**Comment by yanbf** [comment] 2016-06-17 01:31
oh, thank you very much.

but when this issue is merged to master.

**Comment by ekoly** [comment] 2016-06-17 14:29
I don't know, I haven't heard anything from the project admins, potentially it could take a while.

**Comment by rituparnamukherjee** [comment] 2016-06-21 20:50
Hey Guys,

Thanks for pointing this out. We will fix this asap.

**Comment by rituparnamukherjee** [comment] 2016-06-21 20:51
Closing this one. Will track using #208

**Closed by rituparnamukherjee** 2016-06-21 20:51 UTC
